### ISSUE TITLE
Changing sparql endpoint is still not being propagated 

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#152]
I am running the Electron installer. I changed the sparql endpoint to the public one because of some network issues, but it made no difference.

Please take a look

**Comment by devowit** [comment]
possibly fixed in commit 19783b, but it would really help to have more details about the bug and what was expected to happen and did not happen during which requests.

**Comment by devowit** [comment]
(alternately, is it that the newly changed sparql endpoint is not displaying in the settings box in the frontend?)

**Comment by saggu** [comment]
Ok, here is what happened.

The dsbox02 sparql endpoint was not reachable due to some network issues. So the labels for Qnodes were not being fetched in the `output` section of T2WML UI.

I changed the endpoint to the public wikidata one, the labels were still not being fetched. I tried to reload the project and everything. After reloading the SPARQL endpoint went back to dsbox02

**Comment by saggu** [comment]
@devowit how does the label acquisition actually works? Read from wikifier and if not present query the SPARQL endpoint?

**Comment by devowit** [comment]
it reads from the item definitions file (saved into a database) and if not present queries sparql endpoint. 
in issue #154 you also conflated wikifier file with item definitions file, I think discussing merging all three needs to happen, but I don't understand how it would work.

**Comment by devowit** [comment]
@saggu can this be closed? is it still happening?

**Comment by saggu** [comment]
Closing, with recent changes in T2WML, this issue is moot. I'll open a new one if required
