### ISSUE TITLE
Loading a project using a yaml file, does not upload the properties from  the pf/properties.tsv file

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#181]
1. untar the project file somewhere on your filesytem
2. edit the directory attribute of t2wmlproj.yaml file to point to the location where you untar the file (including the name of the project directory)
3. In t2wml click on Load project and browse to the t2wmlproj.yaml file

[region-tutorial-7.tar.gz](https://github.com/usc-isi-i2/t2wml/files/5104950/region-tutorial-7.tar.gz)

You can see the column `D` in the sheet `00_region` is red because it cannot find the properties. The issue is resolved by manually uploading the properties file from `pf/properties.tsv`

**Comment by devowit** [comment]
fixed in 7590cd5aa

**Comment by devowit** [comment]
version 2.3.4
please close when tested ok

**Comment by saggu** [comment]
@devowit I cannot open the project anymore. When I click on `Open Project`, the option to select the `t2wmlproj.yaml` is not there anymore

![image](https://user-images.githubusercontent.com/6811931/95111508-72a2f080-06f4-11eb-9f37-16d5ae1ffbb9.png)


I even tried after changing the name to `project.t2wml`.

Re opening

**Comment by saggu** [comment]
@devowit so I had to change the filename to project.t2wml, but properties are still not being loaded. It might be related to #247

**Comment by saggu** [comment]
Actually it is not related to #247 The property file is still not being loaded. version: 2.3.7

**Comment by devowit** [comment]
in the t2wmlproj.yaml file, the field with the properties file is named property_files instead of entity_files (what we renamed to when we combined properties and items). when i renamed that field, the project loaded fine

**Comment by devowit** [comment]
@saggu is this issue resolved?

**Comment by devowit** [comment]
assuming no response for months means it's been dealt with, closing
