### ISSUE TITLE
KGTK tsv and FIDIL files from restored t2wmlz file do not contain data

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#631]
The KGTK tsv generated from restored t2wmlz file does not contain data.
This happens for FIDIL files as well.

[UN_Median_Population_Age_1631.zip](https://github.com/usc-isi-i2/t2wml/files/7156207/UN_Median_Population_Age_1631.zip)

**Comment by devowit** [comment]
I am pretty sure I have fixed this, it just needs to be deployed and tested...

**Comment by kyao** [comment]
Let me know once it is fixed. I need to do a dump of all the data.

**Comment by devowit** [comment]
I don't know how to deploy the site myself, hopefully @g1eb can do so soon

**Comment by kyao** [comment]
If the fixes are checked in, I can test locally on my machine.

**Comment by kyao** [comment]
@devowit I checked out the latest commits. I am still getting empty results

**Comment by devowit** [comment]
can this be closed now?

**Comment by devowit** [comment]
@kyao has this been resolved? can i close it?

**Comment by kyao** [comment]
fixed
